---
- name: linux
  hosts: linux
  become: false
  vars:
    current_os: linux

  roles:
    - unix
    - linux

- name: macos
  hosts: [macos, media]
  vars:
    current_os: macos

  vars_files:
    - vars/macos.yml

  roles:
    - unix
    - macos

- name: macos_defaults
  hosts: [macos, media]
  become: true
  vars:
    current_os: macos

  vars_files:
    - vars/macos.yml

  vars_prompt:
    -   name: "ansible_become_pass"
        prompt: "Sudo password"
        private: yes

  roles:
    - macos_defaults

- name: windows
  hosts: windows
  become: false
  vars:
    current_os: windows

  roles:
    - windows

- name: media
  hosts: [media]
  become: false
  vars:
    current_os: macos

  vars_files:
    - vars/media.yml

  roles:
    - homebrew
    - jdownloader
    - nfs
