---
- name: linux
  hosts: linux
  become: false
  vars:
    current_os: linux

  roles:
    - unix
    - linux

- name: macos
  hosts: [macos, media]
  vars:
    current_os: macos

  vars_files:
    - vars/macos.yml

  roles:
    - unix
    - macos

- name: windows
  hosts: windows
  become: false
  vars:
    current_os: windows

  roles:
    - windows

- name: media
  hosts: [media]
  become: false
  vars:
    current_os: macos

  vars_files:
    - vars/media.yml

  roles:
    - homebrew
    - jdownloader
    - openwebui
    - watchtower
    - cloudflared
