#!/usr/bin/env bash
HEADPHONE_SINK=$(pactl list short sinks | grep "stereo-game" | cut -f2)
SPEAKER_SINK=$(pactl list short sinks | grep "Creative_Technology" | cut -f2)

ACTIVE_SINK=$(pactl get-default-sink)

SINK_TO_SWITCH_TO=""

if [ "$ACTIVE_SINK" = "$HEADPHONE_SINK" ]; then
    SINK_TO_SWITCH_TO="$SPEAKER_SINK"
elif [ "$ACTIVE_SINK" = "$SPEAKER_SINK" ]; then
    SINK_TO_SWITCH_TO="$HEADPHONE_SINK"
fi

case $BLOCK_BUTTON in
    2) pactl set-default-sink "$SINK_TO_SWITCH_TO" ;;
esac

ACTIVE_SINK=$(pactl get-default-sink)

if [ "$ACTIVE_SINK" = "$HEADPHONE_SINK" ]; then
    echo "🎧"
elif [ "$ACTIVE_SINK" = "$SPEAKER_SINK" ]; then
    echo "🔊"
else
    echo "unknown"
fi