# roles/openwebui/tasks/main.yml
---
- name: Ensure OpenWebUI directory structure exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ target_user }}"
    group: "staff"
    mode: '0755'
  loop:
    - "{{ docker_base_dir }}"
    - "{{ docker_base_dir }}/openwebui"
    - "{{ docker_base_dir }}/openwebui/config"
  become: no

- name: Template OpenWebUI Docker Compose file
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ docker_base_dir }}/openwebui/docker-compose.yml"
    owner: "{{ target_user }}"
    group: "staff"
    mode: '0644'
  become: no
  notify: Restart openwebui

- name: Ensure OpenWebUI service is running
  community.docker.docker_compose_v2:
    project_src: "{{ docker_base_dir }}/openwebui"
    files:
      - "{{ docker_base_dir }}/openwebui/docker-compose.yml"
    state: present
    recreate: auto
    docker_cli: /usr/local/bin/docker
  become: no