---
- name: setup auto_nfs file
  ansible.builtin.template:
    src: templates/auto_nfs
    dest: /etc/auto_nfs
  become: yes
  notify: Reload automountd

- name: setup auto_master file
  ansible.builtin.template:
    src: templates/auto_master
    dest: /etc/auto_master
  become: yes
  notify: Reload automountd