# roles/homebrew/tasks/main.yml
---
- name: Update Homebrew repository and update all packages
  community.general.homebrew:
    update_homebrew: yes
    upgrade_all: yes
  become: no

- name: Install specified homebrew packages
  community.general.homebrew:
    name: "{{ homebrew_packages }}"
    state: present
  become: no