---
- name: Ensure Chatterino2 directories exist
  win_file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_env.USERPROFILE }}\\AppData\\Roaming\\Chatterino2\\Settings"

- name: Delete existing Chatterino2 config files if present
  win_file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_env.USERPROFILE }}\\AppData\\Roaming\\Chatterino2\\Settings\\commands.json"
    - "{{ ansible_env.USERPROFILE }}\\AppData\\Roaming\\Chatterino2\\Settings\\settings.json"
    - "{{ ansible_env.USERPROFILE }}\\AppData\\Roaming\\Chatterino2\\Settings\\window-layout.json"

- name: Copy Chatterino2 config files
  ansible.windows.win_copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.USERPROFILE }}\\AppData\\Roaming\\Chatterino2\\Settings\\{{ item | basename }}"
  loop:
    - "{{ playbook_dir }}/files/chatterino/commands.json"
    - "{{ playbook_dir }}/files/chatterino/settings.json"
    - "{{ playbook_dir }}/files/chatterino/window-layout.json"
