---
- name: Ensure Chatterino2 directories exist
  win_file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_env.USERPROFILE }}\\AppData\\Roaming\\Chatterino2\\Settings"

- name: Delete existing Chatterino2 config files if present
  win_file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_env.USERPROFILE }}\\AppData\\Roaming\\Chatterino2\\Settings\\commands.json"
    - "{{ ansible_env.USERPROFILE }}\\AppData\\Roaming\\Chatterino2\\Settings\\window-layout.json"

- name: Symlink Chatterino2 config files
  ansible.windows.win_shell: |
    New-Item -ItemType SymbolicLink -Path "{{ ansible_env.USERPROFILE }}\AppData\Roaming\Chatterino2\Settings\commands.json" -Target "{{ ansible_env.USERPROFILE }}\dotfiles\.local\share\chatterino\Settings\commands.json"
    New-Item -ItemType SymbolicLink -Path "{{ ansible_env.USERPROFILE }}\AppData\Roaming\Chatterino2\Settings\window-layout.json" -Target "{{ ansible_env.USERPROFILE }}\dotfiles\.local\share\chatterino\Settings\window-layout.json"
  args:
    creates: "{{ ansible_env.USERPROFILE }}\\AppData\\Roaming\\Chatterino2\\Settings\\commands.json"
