---
# Common tasks shared across all platforms

- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ansible_env.HOME }}/.vim/colors"
    - "{{ ansible_env.HOME }}/.vim/autoload"
    - "{{ ansible_env.HOME }}/.config/alacritty"
    - "{{ ansible_env.HOME }}/.config/zsh"
    - "{{ ansible_env.HOME }}/.config/streamlink"

- name: Symlink common configuration files
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest | default(item.src) }}"
    state: link
    force: "{{ item.force | default(false) }}"
  loop:
    - { src: ".vimrc" }
    - { src: ".vim/colors/onedark.vim" }
    - { src: ".vim/autoload/onedark.vim" }
    - { src: ".zshrc" }
    - { src: ".config/alacritty/alacritty.yml" }
    - { src: ".tmux.conf" }
    - { src: ".config/zsh/git.sh" }
    - { src: ".config/streamlink/config" }
