---
- name: Stat live agent config
  ansible.builtin.stat:
      path: "{{ ansible_env.HOME }}/{{ agent_config.live }}"
  register: agent_config_live_stat

- name: Sync agent config back to repo
  when:
      - agent_config.sync_back | default(true)
      - agent_config_live_stat.stat.exists
      - agent_config_live_stat.stat.isreg
  ansible.builtin.copy:
      src: "{{ ansible_env.HOME }}/{{ agent_config.live }}"
      dest: "{{ role_path }}/files/{{ agent_config.repo }}"
      remote_src: true
      force: true

- name: Ensure agent config symlink
  ansible.builtin.file:
      src: "{{ role_path }}/files/{{ agent_config.repo }}"
      dest: "{{ ansible_env.HOME }}/{{ agent_config.live }}"
      state: link
      force: true
